/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Exceptions.AlturaVaziaException;
import Exceptions.CodigoVazioException;
import Exceptions.PesoVazioException;
import Exceptions.StringVaziaException;
import control.AtletaControl;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class telaAtleta extends javax.swing.JFrame {

    private AtletaControl atlCad;
    
    /**
     * Creates new form telaAtleta
     */
    public telaAtleta() {
        atlCad = new AtletaControl();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnQtdma = new javax.swing.JButton();
        btnQtdme = new javax.swing.JButton();
        btnMaisAlt = new javax.swing.JButton();
        btnMedPe = new javax.swing.JButton();
        btnBuscaN = new javax.swing.JButton();
        btnBuscaI = new javax.swing.JButton();
        btnBuscaC = new javax.swing.JButton();
        btnBuscaP = new javax.swing.JButton();
        btnBuscaA = new javax.swing.JButton();
        txtBuscaN = new javax.swing.JTextField();
        txtBuscaI = new javax.swing.JTextField();
        txtBuscaC = new javax.swing.JTextField();
        txtBuscaP = new javax.swing.JTextField();
        txtBuscaA = new javax.swing.JTextField();
        btnExc = new javax.swing.JButton();
        lblCodExc = new javax.swing.JLabel();
        txtCodExc = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome:");

        lblIdade.setText("Idade:");

        lblCod.setText("Codigo:");

        lblPeso.setText("Peso:");

        lblAltura.setText("Altura:");

        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });

        btnAdd.setText("Adicionar Atleta");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnQtdma.setText("Quantidade maiores");
        btnQtdma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQtdmaActionPerformed(evt);
            }
        });

        btnQtdme.setText("Quantidade menores");
        btnQtdme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQtdmeActionPerformed(evt);
            }
        });

        btnMaisAlt.setText("Atleta mais alto");
        btnMaisAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisAltActionPerformed(evt);
            }
        });

        btnMedPe.setText("Média peso");
        btnMedPe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedPeActionPerformed(evt);
            }
        });

        btnBuscaN.setText("Busca por Nome");
        btnBuscaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaNActionPerformed(evt);
            }
        });

        btnBuscaI.setText("Busca por Idade");
        btnBuscaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaIActionPerformed(evt);
            }
        });

        btnBuscaC.setText("Busca por Codigo");
        btnBuscaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCActionPerformed(evt);
            }
        });

        btnBuscaP.setText("Busca por Peso");
        btnBuscaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPActionPerformed(evt);
            }
        });

        btnBuscaA.setText("Busca por Altura");
        btnBuscaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaAActionPerformed(evt);
            }
        });

        btnExc.setText("Excluir Atleta");
        btnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcActionPerformed(evt);
            }
        });

        lblCodExc.setText("Código de quem deseja excluir:");

        btnBuscar.setText("Buscar Atletas");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPeso)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblIdade)
                                        .addComponent(lblNome)
                                        .addComponent(lblCod))
                                    .addComponent(lblAltura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnBuscaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBuscaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBuscaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnBuscaI, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBuscaN, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscaP)
                                    .addComponent(txtBuscaA)
                                    .addComponent(txtBuscaI)
                                    .addComponent(txtBuscaC)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(txtBuscaN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQtdma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMedPe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQtdme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMaisAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCodExc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodExc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscaN)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaI)
                    .addComponent(txtBuscaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaC)
                    .addComponent(txtBuscaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaP)
                    .addComponent(txtBuscaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaA)
                    .addComponent(txtBuscaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodExc)
                        .addComponent(txtCodExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQtdme)
                        .addComponent(btnMaisAlt)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQtdma)
                    .addComponent(btnMedPe)
                    .addComponent(btnExc))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    
       try{
           String nome = this.txtNome.getText();
           if(nome.equals(""))
           {
               throw new StringVaziaException();
           }
           int idade = Integer.parseInt(this.txtIdade.getText());
           
           double Peso = Double.parseDouble(this.txtPeso.getText());
             if(Peso<=0)
           {
               throw new PesoVazioException();
           }
           
           double Altura = Double.parseDouble(this.txtAltura.getText());
             if(Altura<=0)
           {
               throw new AlturaVaziaException();
           }
           
           int cod = Integer.parseInt(this.txtCod.getText());
             if(cod<=0)
           {
               throw new CodigoVazioException();
           }
           
             atlCad.cadastrarAtleta(nome, idade, Peso, Altura, cod);
            
       }
       catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null, "Idade deve ser um número positivo");
           this.txtIdade.setText("");
           this.txtIdade.requestFocus();
       }
       
       catch(StringVaziaException e1)
       {
             JOptionPane.showMessageDialog(null, e1.getMessage());
              this.txtNome.setText("");
              this.txtNome.requestFocus();
       }
       
              
       catch(PesoVazioException e2)
       {
           JOptionPane.showMessageDialog(null, e2.getMessage());
           this.txtPeso.setText("");
           this.txtPeso.requestFocus();
       }
       
         catch(AlturaVaziaException e3)
       {
           JOptionPane.showMessageDialog(null, e3.getMessage());
           this.txtAltura.setText("");
           this.txtAltura.requestFocus();
       }
         catch(CodigoVazioException e4)
       {
           JOptionPane.showMessageDialog(null, e4.getMessage());
           this.txtCod.setText("");
           this.txtCod.requestFocus();
       }
      
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnQtdmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQtdmeActionPerformed
   
             JOptionPane.showMessageDialog(null, "Quantidade de menores de idade: "+atlCad.qtdmeno()); 
        
    }//GEN-LAST:event_btnQtdmeActionPerformed

    private void btnMaisAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisAltActionPerformed
            JOptionPane.showMessageDialog(null, " "+atlCad.maisAlto()); 
    }//GEN-LAST:event_btnMaisAltActionPerformed

    private void btnQtdmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQtdmaActionPerformed
         
           JOptionPane.showMessageDialog(null, "Quantidade de maiores de idade: "+atlCad.qtdmai()); 

    }//GEN-LAST:event_btnQtdmaActionPerformed

    private void btnMedPeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedPeActionPerformed
           JOptionPane.showMessageDialog(null, "Media de pesos dos atletas: "+atlCad.mediaPeso()); 
    }//GEN-LAST:event_btnMedPeActionPerformed

    private void btnBuscaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNActionPerformed
      String nome1= txtBuscaN.getText();
        
      String inf = atlCad.buscaNo(nome1);
       JOptionPane.showMessageDialog(null,""+inf+" \n"); 
    }//GEN-LAST:event_btnBuscaNActionPerformed

    private void btnBuscaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaIActionPerformed
   int ida = Integer.parseInt(this.txtBuscaI.getText());    
   String inf = atlCad.buscaida(ida);
   JOptionPane.showMessageDialog(null,""+inf+" \n"); 

    }//GEN-LAST:event_btnBuscaIActionPerformed

    private void btnBuscaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCActionPerformed
      int cod1 =  Integer.parseInt(this.txtBuscaC.getText());        
      String inf = atlCad.buscacod(cod1);
      JOptionPane.showMessageDialog(null,""+inf+" \n"); 

    }//GEN-LAST:event_btnBuscaCActionPerformed

    private void btnBuscaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPActionPerformed
      double pes = Double.parseDouble(this.txtBuscaP.getText());
      String inf = atlCad.buscapeso(pes);
      JOptionPane.showMessageDialog(null,""+inf+" \n"); 

    }//GEN-LAST:event_btnBuscaPActionPerformed

    private void btnBuscaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaAActionPerformed
     double alt = Double.parseDouble(this.txtBuscaA.getText());
     String inf = atlCad.buscaAlt(alt);       
     JOptionPane.showMessageDialog(null,""+inf+" \n"); 

    }//GEN-LAST:event_btnBuscaAActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
   String excCd = txtCodExc.getText();
   int res = JOptionPane.showConfirmDialog(null, "deseja excluir o atleta de código: "+excCd+"?");
   if (res==0)
   {
       atlCad.excluir(excCd);
   }

    }//GEN-LAST:event_btnExcActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String mostrad =atlCad.mostradad();
        JOptionPane.showMessageDialog(null,""+mostrad+" \n"); 
        
        

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAtleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscaA;
    private javax.swing.JButton btnBuscaC;
    private javax.swing.JButton btnBuscaI;
    private javax.swing.JButton btnBuscaN;
    private javax.swing.JButton btnBuscaP;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExc;
    private javax.swing.JButton btnMaisAlt;
    private javax.swing.JButton btnMedPe;
    private javax.swing.JButton btnQtdma;
    private javax.swing.JButton btnQtdme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCodExc;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBuscaA;
    private javax.swing.JTextField txtBuscaC;
    private javax.swing.JTextField txtBuscaI;
    private javax.swing.JTextField txtBuscaN;
    private javax.swing.JTextField txtBuscaP;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCodExc;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
